### ISSUE TITLE
Memory size

### ISSUE THREAD

**Issue by fourroses666** [manse/sass.modx#3]
Hi Manse,

Long time ago I used this plugin but would like to try it again.
My fork has a different version (no haml) but worked before.
https://github.com/fourroses666/sass.modx

I'm getting the below error; phpinfo says I have 128M. 
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /home/xxx/domains/xxx.nl/public_html/xxx/assets/plugins/sass/script/SassScriptLexer.php on line 114`

**Comment by manse** [comment]
Hi fourroses666,

Please refer this.
https://stackoverflow.com/questions/12264253/allowed-memory-size-of-134217728-bytes-exhausted#answer-12264306

**Comment by fourroses666** [comment]
Asked the host to increase the memory and is now 512M, not solved, will try on an other host.
Can't remember how I fixed it a couple of years ago. :(

max_execution_time | 30
max_file_uploads | 20
max_input_nesting_level | 64
max_input_time | 60
max_input_vars | 1000 
memory_limit | 512M

**Comment by fourroses666** [comment]
don't know how to solve
